### PR TITLE
Add condition: Assertion in check env 

### PR DESCRIPTION
**Pull request by Eikinho**
I just removed the assert and added a condition to check if FLASK_ENV is None. So, if FLASK_ENV is not set, assumes development configs.

### CODE REVIEW

**Comment by pedrooa** [comment]
lgm!

**Review by pedrooa — APPROVED** [review]
lgm!

**Review by pedrooa — CHANGES_REQUESTED** [review]
lgm!

Just bump the version on `setup.py` fila so a new release is created.

**Comment by Eikinho** [comment]
Done!

**Review by pedrooa — APPROVED** [review]
Approved

**Pull request merged**
